### PR TITLE
Extend Dimmed View on HTML Messages

### PR DESCRIPTION
**Pull request by jjgp**
This PR to our fork of the Leanplum-iOS-SDK extends the dimmed view on HTML messages to over the safe areas:

update

For more context refer to this issue: [issue](https://github.com/stockx/ios/issues/2071)

The other messages in this category include: 
Screen Shot 2019-04-16 at 12 32 17 PM

Screenshots of the messages with the changes are shown below...

### Banner
Screen Shot 2019-04-16 at 12 22 20 PM

### Star Rating
Screen Shot 2019-04-16 at 12 23 45 PM

Once this PR merges it will be pointed to in the Podfile in stockx/ios

### CODE REVIEW

**Comment by jjgp** [comment]
Here is what the banner and rating looks like on iPhone X:
Screen Shot 2019-04-16 at 3 33 52 PM

Screen Shot 2019-04-16 at 3 31 22 PM

**Comment by jeffaburt** [comment]
I'm all good with the changes here. I recommend we treat this as `2.4.1.1`, which tells us two things: 1) we're based off of 2.4.1 and 2) we've added some of our own commits on top of Leanplum's 2.4.1 (hence the trailing `.1`).

To do this, we usually:

- Update the version in the podspec
- `git tag 2.4.1.1 && git push origin 2.4.1.1`

Then, we can just close this PR and leave `master` as-is. That way, when looking at tags, our custom commits are always at the top of the list to make it super obvious.

**Comment by jjgp** [comment]
@jeffaburt sounds good i will do this and add a PR in ios develop to use 2.4.1.1

**Comment by LaurentShala** [comment]
@jjgp This PR looks good to me, going to hold off on merging it since @jeffaburt requested changes and has not approved them as of yet!

**Comment by jjgp** [comment]
closed and used here: https://github.com/stockx/ios/pull/2077

**Comment by jjgp** [comment]
@LaurentShala we are going to close this one and just have the tag point to the branch. we good here

**Pull request closed without merging**
